# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0726b86bc7964c71f1052d7c6dc7223d1d1130af5f2b65b90909c6a0cf6b72fbd9cab3832c6011faad391bdab93b23e7ea167a879d3f3ce7668362ef5099adee

test:
  secret_key_base: be0bb03fd81bd585dbfd10eda0544a52425d82e278bc47eee755a645017505c111b4f935cbbd3ca841fa7191d7198f1faa1bcfe7a58aaa2f6e38b3a4e4c50be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
